spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/~~~~~?serverZoneId=Asia/Seoul&sslMode=DISABLED
    username: ~~~~~
    password: ~~~~~
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
        maximum-pool-size: 50
        minimum-idle: 10
        idle-timeout: 600000
        max-lifetime: 1800000
        connection-timeout: 30000
        pool-name: SpringBatchHikariCP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    jdbc:
      platform: mysql
      initialize-schema: always
    job:
      enabled: false

logging:
  level:
    com.zaxxer.hikari: INFO
    com.zaxxer.hikari.HikariConfig: INFO
    com.zaxxer.hikari.pool.HikariPool: INFO
    org.springframework.batch: INFO
    org.springframework.jdbc: INFO
    org.springframework.boot.autoconfigure.jdbc: INFO
    com.example.springbatchkotlin: INFO

